Repository boostcampwm-2024/iOS03-SniffMeet, pull requests merged in 2024-11, with the labels that each got.

#7 [add] PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE/default_template.md
Labels: project

#12 [chore] SwiftLint 설정 파일을 추가했습니다.
  SniffMeet/SniffMeet/.swiftlint.yml
Labels: project

#10 [add] 프로젝트 구조에 맞게 폴더링 작업 및 디자인 에셋을 추가했습니다.
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Assets.xcassets/AppIcon.appiconset/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  SniffMeet/SniffMeet/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/ImagePlaceholder.imageset/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/ImagePlaceholder.imageset/image-placeholder.png
  SniffMeet/SniffMeet/Resource/Assets.xcassets/ImagePlaceholder.imageset/image-placeholder@2x.png
  SniffMeet/SniffMeet/Resource/Assets.xcassets/ImagePlaceholder.imageset/image-placeholder@3x.png
  SniffMeet/SniffMeet/Resource/Base.lproj/LaunchScreen.storyboard
  SniffMeet/SniffMeet/Resource/Info.plist
  SniffMeet/SniffMeet/Source/App/AppDelegate.swift
  SniffMeet/SniffMeet/Source/App/SceneDelegate.swift
Labels: project

#16 [design] MainColorSet을 프로젝트 에셋에 추가했습니다.
  SniffMeet/SniffMeet/Resource/Assets.xcassets/MainColorSet/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/MainColorSet/MainBeige.colorset/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/MainColorSet/MainBrown.colorset/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/MainColorSet/MainNavy.colorset/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/MainColorSet/MainWhite.colorset/Contents.json
Labels: project

#18 [fix] App파일 관련 문제 해결
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/.swiftlint.yml
  SniffMeet/SniffMeet/Source/App/SceneDelegate.swift
Labels: fix

#20 [design] Launch Screen 설정
  SniffMeet/SniffMeet/Resource/Assets.xcassets/AppImage.imageset/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/AppImage.imageset/Frame 121.svg
  SniffMeet/SniffMeet/Resource/Assets.xcassets/AppImage.imageset/Frame 122.svg
  SniffMeet/SniffMeet/Resource/Assets.xcassets/AppImage.imageset/Frame 123.svg
  SniffMeet/SniffMeet/Resource/Base.lproj/LaunchScreen.storyboard
  SniffMeet/SniffMeet/Source/App/AppDelegate.swift
  SniffMeet/SniffMeet/Source/App/SceneDelegate.swift
Labels: design

#21 [design] 공통 컴포넌트 생성
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Resource/Assets.xcassets/MainColorSet/SubGray1.colorset/Contents.json
  SniffMeet/SniffMeet/Source/Common/Extension + Navigation.swift
  SniffMeet/SniffMeet/Source/Common/InputTextField.swift
  SniffMeet/SniffMeet/Source/Common/KeywordButton.swift
  SniffMeet/SniffMeet/Source/Common/KeywordView.swift
  SniffMeet/SniffMeet/Source/Common/PrimaryButton.swift
Labels: design

#22 [docs] README.md 업데이트
  README.md
Labels: documentation

#25 [design] 프로필 이미지 및 닉네임 입력 화면 생성
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileSetupView.swift
  SniffMeet/SniffMeet/Source/Common/Extension + UIView.swift
  SniffMeet/SniffMeet/Source/Common/PrimaryButton.swift
Labels: feature, design

#27 [project] 린트 룰 수정 및 PR 템플릿 경로 수정
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
  SniffMeet/SniffMeet/.swiftlint.yml
Labels: project

#29 [feat, ui] 메인 화면 뷰 그리기
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Home/Main/View/HomeViewController.swift
  SniffMeet/SniffMeet/Source/Home/Main/View/ProfileCardView.swift
Labels: feature, UI

#32 [design] 반려견 정보 입력 화면 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/App/SceneDelegate.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileInputView.swift
  SniffMeet/SniffMeet/Source/Common/KeywordButton.swift
Labels: feature, design

#41 [feat] 비활성화 배경색 지정 및 키보드 extension 분리
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileInputView.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileSetupView.swift
  SniffMeet/SniffMeet/Source/Common/Extension + Keyboard.swift
  SniffMeet/SniffMeet/Source/Common/Extension + Navigation.swift
  SniffMeet/SniffMeet/Source/Common/InputTextField.swift
  SniffMeet/SniffMeet/Source/Common/KeywordButton.swift
  SniffMeet/SniffMeet/Source/Common/KeywordView.swift
  SniffMeet/SniffMeet/Source/Common/PrimaryButton.swift
  SniffMeet/SniffMeet/Source/Common/SNMColor.swift
  SniffMeet/SniffMeet/Source/Home/Main/View/ProfileCardView.swift
Labels: feature, design

#36 [feat] 메인 탭 바 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/App/SceneDelegate.swift
  SniffMeet/SniffMeet/Source/Home/Main/HomeModuleBuilder.swift
  SniffMeet/SniffMeet/Source/Tab/TabBarModuleBuilder.swift
  SniffMeet/SniffMeet/Source/Tab/View/TabBarController.swift
Labels: feature, UI

#38 [feat] BaseView / ViewController 추가
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/BaseView.swift
  SniffMeet/SniffMeet/Source/Common/BaseViewController.swift
Labels: feature

#43 [feat] 앱 라우터 생성 및 SceneDelegate에 적용
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/App/AppRouter.swift
  SniffMeet/SniffMeet/Source/App/SceneDelegate.swift
Labels: feature, project

#44 [feat] KeychainManager / UserDefaultsManager 구현
  SniffMeet/SNMPersistenceTests/KeychainTests.swift
  SniffMeet/SNMPersistenceTests/UserDefaultsTests.swift
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet.xcodeproj/xcshareddata/xcschemes/SNMPersistenceTests.xcscheme
  SniffMeet/SniffMeet.xcodeproj/xcshareddata/xcschemes/SniffMeet.xcscheme
  SniffMeet/SniffMeet/Source/Persistence/KeychainManager.swift
  SniffMeet/SniffMeet/Source/Persistence/UserDefaultsManager.swift
Labels: feature, test

#46 [feat] MPCAdvertiser, MPCBrowser, MPConnectionManager 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Resource/Info.plist
  SniffMeet/SniffMeet/Source/LocalNetwork/MPC/MPCAdvertiser.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/MPC/MPCBroswer.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/MPC/MPConnectionManager.swift
Labels: feature

#52 [feat] 반려견 정보 입력 기능 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/App/AppRouter.swift
  SniffMeet/SniffMeet/Source/App/SceneDelegate.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Entity/Dog.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Interactor/DataManager.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Interactor/ProfileCreateInteractor.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Interactor/SaveInfoUseCase.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Presenter/ProfileCreatePresenter.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Presenter/ProfileInputPresenter.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Router/ProfileCreateRouter.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Router/ProfileInputRouter.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileCreateViewController.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileInputViewController.swift
  SniffMeet/SniffMeet/Source/Common/Extension + Keyboard.swift
  SniffMeet/SniffMeet/Source/Home/Main/HomeModuleBuilder.swift
Labels: feature

#51 [feat] SNMNetwork 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/SNMNetwork/AnyEncodable.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Endpoint.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/NetworkProvider.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/SNMNetworkResponse.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/SNMRequestConvertible.swift
Labels: feature

#53 [feat] NIManager 추가, NearbyInteraction 사용해 기기 간 거리 파악
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Resource/Info.plist
  SniffMeet/SniffMeet/Source/Home/Main/View/HomeViewController.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/MPC/MPCAdvertiser.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/MPC/MPCBroswer.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/MPC/MPCManager.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/NI/NIManager.swift
Labels: feature

#54 [docs] README.md 수정
  README.md
Labels: documentation

#55 [fix] .pbxproj 파일 수정
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
Labels: fix

#57 [ feat] 네트워크 requestType 추가
  SniffMeet/SNMNetworkTests/AnyEncodableTests.swift
  SniffMeet/SNMNetworkTests/EndpointTests.swift
  SniffMeet/SNMNetworkTests/MultipartFormDataTests.swift
  SniffMeet/SNMNetworkTests/SNMNetworkTests.swift
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet.xcodeproj/xcshareddata/xcschemes/SNMNetworkTests.xcscheme
  SniffMeet/SniffMeet/Source/SNMNetwork/Core/Endpoint.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Core/HTTPStatusCode.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Core/MultipartFormData.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Core/NetworkProvider.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Core/SNMNetworkResponse.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Core/SNMRequestConvertible.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Core/SNMRequestType.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Helper/AnyEncodable.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Helper/Data + append.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Helper/URLRequest + append.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Mock/MockRequest.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Mock/MockURLProtocol.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/NetworkProvider.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/SNMRequestConvertible.swift
Labels: feature, refactor, test

#60 [feat] UIControl + Publisher 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/UIControl + Publisher.swift
Labels: feature

#63 [design] 산책 요청 보내기 뷰
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Resource/Base.lproj/LaunchScreen.storyboard
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Router/ProfileCreateRouter.swift
  SniffMeet/SniffMeet/Source/Common/LayoutConstant.swift
  SniffMeet/SniffMeet/Source/Entity/Dog.swift
  SniffMeet/SniffMeet/Source/Repository/Auth/DataManager.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestWalk.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveInfoUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Interactor/RequestWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Presenter/RequestWalkPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Router/RequestWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/CardPresentationController.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/RequestWalkViewController.swift
Labels: design

#64 [fix] 프로필 생성 뷰~메인 뷰 프로필 데이터 연결
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/App/Routable.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileCreateViewController.swift
  SniffMeet/SniffMeet/Source/Home/Main/HomeModuleBuilder.swift
  SniffMeet/SniffMeet/Source/Home/Main/Interactor/HomeInteractor.swift
  SniffMeet/SniffMeet/Source/Home/Main/Presenter/HomePresenter.swift
  SniffMeet/SniffMeet/Source/Home/Main/Router/HomeRouter.swift
  SniffMeet/SniffMeet/Source/Home/Main/View/HomeViewController.swift
  SniffMeet/SniffMeet/Source/Repository/Auth/DataManager.swift
  SniffMeet/SniffMeet/Source/UseCase/LoadDogInfoUseCase.swift
Labels: feature

#68 [feat] SNMLogger 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/SNMLogger.swift
Labels: feature

#62 [feat] supabase 디렉토리 및 Auth 기능 추가
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/App/AppRouter.swift
  SniffMeet/SniffMeet/Source/App/SceneDelegate.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Core/SNMRequestConvertible.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Helper/URLRequest + append.swift
  SniffMeet/SniffMeet/Source/Supabase/Auth/Entity/Request/SupabaseTokenRequest.swift
  SniffMeet/SniffMeet/Source/Supabase/Auth/Entity/Response/SupabaseRefreshResponse.swift
  SniffMeet/SniffMeet/Source/Supabase/Auth/Entity/Response/SupabaseSessionResponse.swift
  SniffMeet/SniffMeet/Source/Supabase/Auth/Entity/Response/SupabaseUserResponse.swift
  SniffMeet/SniffMeet/Source/Supabase/Auth/Entity/SupabaseSession.swift
  SniffMeet/SniffMeet/Source/Supabase/Auth/Entity/SupabaseUser.swift
  SniffMeet/SniffMeet/Source/Supabase/Auth/SessionManager.swift
  SniffMeet/SniffMeet/Source/Supabase/Auth/SupabaseAuthError.swift
  SniffMeet/SniffMeet/Source/Supabase/Auth/SupabaseAuthManager.swift
  SniffMeet/SniffMeet/Source/Supabase/Auth/SupabaseRequest.swift
  SniffMeet/SniffMeet/Source/Supabase/SupabaseConfig.swift
Labels: feature

#70 [design] 메이트 요청시 교환하는 프로필 카드 뷰
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/LayoutConstant.swift
  SniffMeet/SniffMeet/Source/Common/SNMFont.swift
  SniffMeet/SniffMeet/Source/Entity/Dog.swift
  SniffMeet/SniffMeet/Source/Mate/RequestMate/Interactor/RequestMateInteractor.swift
  SniffMeet/SniffMeet/Source/Mate/RequestMate/Presenter/RequestMatePresenter.swift
  SniffMeet/SniffMeet/Source/Mate/RequestMate/Router/RequestMateRouter.swift
  SniffMeet/SniffMeet/Source/Mate/RequestMate/View/RequestMateViewController.swift
Labels: feature, design

#71 [design] 산책 요청 수락 화면 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/LayoutConstant.swift
  SniffMeet/SniffMeet/Source/Common/PaddingLabel.swift
  SniffMeet/SniffMeet/Source/Common/SNMColor.swift
  SniffMeet/SniffMeet/Source/Entity/Dog.swift
  SniffMeet/SniffMeet/Source/Entity/WalkRequest.swift
  SniffMeet/SniffMeet/Source/UseCase/FetchRequestUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestWalkUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RespondWalkRequestUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveInfoUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Router/RequestWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/LocationSelectionView.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/ProfileView.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/RequestWalkViewController.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Interactor/RespondWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Presenter/RespondWalkPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Router/RespondWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/View/RespondWalkViewController.swift
Labels: design

#80 [feat] 반려견 정보 저장 기능 구현
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Presenter/ProfileCreatePresenter.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileCreateViewController.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileInputViewController.swift
  SniffMeet/SniffMeet/Source/Common/Extension + Navigation.swift
  SniffMeet/SniffMeet/Source/Entity/Dog.swift
  SniffMeet/SniffMeet/Source/Home/Main/Presenter/HomePresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/View/RespondWalkViewController.swift
Labels: feature, design

#77 [design/feat] 산책 장소 선택 뷰를 구현했습니다.
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Resource/Info.plist
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileInputViewController.swift
  SniffMeet/SniffMeet/Source/UseCase/ConvertLocationToTextUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestLocationAuthUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUserLocationUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Interactor/SelectLocationInteractor.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Presenter/RequestWalkPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Presenter/SelectLocationPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Router/RequestWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Router/SelectLocationRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/SelectLocationModuleBuildable.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/RequestWalkViewController.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/SelectLocationViewController.swift
Labels: feature, design

#78 [feat] Supabase database 레이어 추가
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Supabase/Auth/SupabaseAuthManager.swift
  SniffMeet/SniffMeet/Source/Supabase/Auth/SupabaseRequest.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseManager.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseRequest.swift
  SniffMeet/SniffMeet/Source/Supabase/SupabaseError.swift
Labels: feature

#85 [design] WalkLogListView 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/App/AppRouter.swift
  SniffMeet/SniffMeet/Source/Common/LayoutConstant.swift
  SniffMeet/SniffMeet/Source/Common/SNMColor.swift
  SniffMeet/SniffMeet/Source/Common/SNMFont.swift
  SniffMeet/SniffMeet/Source/Entity/WalkLog.swift
  SniffMeet/SniffMeet/Source/Walk/WalkLog/WalkLogList/View/WalkLogCell.swift
  SniffMeet/SniffMeet/Source/Walk/WalkLog/WalkLogList/View/WalkLogListViewController.swift
  SniffMeet/SniffMeet/Source/Walk/WalkLog/WalkLogList/View/WalkLogPageViewController.swift
Labels: design

#83 [design] WalkLogPageViewController 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/App/AppRouter.swift
  SniffMeet/SniffMeet/Source/Common/LayoutConstant.swift
  SniffMeet/SniffMeet/Source/Common/SNMColor.swift
  SniffMeet/SniffMeet/Source/Common/SNMFont.swift
  SniffMeet/SniffMeet/Source/Common/SNMLineTabBar.swift
  SniffMeet/SniffMeet/Source/Entity/WalkLog.swift
  SniffMeet/SniffMeet/Source/Walk/WalkLog/WalkLogList/View/WalkLogCell.swift
  SniffMeet/SniffMeet/Source/Walk/WalkLog/WalkLogList/View/WalkLogListViewController.swift
  SniffMeet/SniffMeet/Source/Walk/WalkLog/WalkLogList/View/WalkLogPageViewController.swift
Labels: design

#93 [feat] Filemanager를 이용하여 이미지를 관리하는 타입 구현
  SniffMeet/SNMPersistenceTests/FileManagerTest.swift
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Persistence/SNMFileManager.swift
Labels: feature

#92 [feat] 프로필 이미지 저장 로직 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Interactor/ProfileCreateInteractor.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Presenter/ProfileCreatePresenter.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Router/ProfileCreateRouter.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileCreateViewController.swift
  SniffMeet/SniffMeet/Source/Common/Environment.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveProfileImageUseCase.swift
Labels: feature

#97 [feat] 프로필 드랍 기능 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Resource/Assets.xcassets/TestDoosik.imageset/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/TestDoosik.imageset/Doosik.png
  SniffMeet/SniffMeet/Resource/Info.plist
  SniffMeet/SniffMeet/Source/App/Routable.swift
  SniffMeet/SniffMeet/Source/Entity/Dog.swift
  SniffMeet/SniffMeet/Source/Entity/MateRequest.swift
  SniffMeet/SniffMeet/Source/Home/Main/Presenter/HomePresenter.swift
  SniffMeet/SniffMeet/Source/Home/Main/Router/HomeRouter.swift
  SniffMeet/SniffMeet/Source/Home/Main/View/HomeViewController.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/MPC/MPCAdvertiser.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/MPC/MPCBroswer.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/MPC/MPCManager.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/NI/NIManager.swift
  SniffMeet/SniffMeet/Source/Mate/RequestMate/Router/RequestMateRouter.swift
  SniffMeet/SniffMeet/Source/Mate/RequestMate/View/RequestMateViewController.swift
Labels: feature

#90 [design] 알림 리스트 뷰(NotificationListViewController) 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/SNMColor.swift
  SniffMeet/SniffMeet/Source/Entity/PushNotification.swift
  SniffMeet/SniffMeet/Source/Home/Main/View/NotificationCell.swift
  SniffMeet/SniffMeet/Source/Home/Main/View/NotificationListViewController.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/MPC/MPCAdvertiser.swift
Labels: design

#103 [feat] 메이트 요청을 응답하는 usecase 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Repository/Auth/DataManager.swift
  SniffMeet/SniffMeet/Source/UseCase/AcceptMateRequestUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveInfoUseCase.swift
Labels: feature

#102 [feat] Profile Drop 동작시 로컬 DB에서 가져와 데이터 표시
  SniffMeet/SniffMeet/Resource/Info.plist
  SniffMeet/SniffMeet/Source/Entity/Dog.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/MPC/MPCManager.swift
  SniffMeet/SniffMeet/Source/Mate/RequestMate/Presenter/RequestMatePresenter.swift
  SniffMeet/SniffMeet/Source/Mate/RequestMate/View/RequestMateViewController.swift
Labels: feature

#105 [feat] 익명 로그인 이후 시점에 입력받은 정보 서버에 저장
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Interactor/ProfileCreateInteractor.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Presenter/ProfileCreatePresenter.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Router/ProfileCreateRouter.swift
  SniffMeet/SniffMeet/Source/Entity/UserInfo.swift
  SniffMeet/SniffMeet/Source/Supabase/Auth/Entity/SupabaseUser.swift
  SniffMeet/SniffMeet/Source/Supabase/Auth/SupabaseAuthManager.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUserInfoRemoteUseCase.swift
Labels: feature

#106 [feat] 산책 요청 받는 기능 유즈케이스 모두 적용 (but 유즈케이스가 구현이 안됨)
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/PaddingLabel.swift
  SniffMeet/SniffMeet/Source/Common/SNMColor.swift
  SniffMeet/SniffMeet/Source/Entity/WalkRequest.swift
  SniffMeet/SniffMeet/Source/UseCase/AcceptMateRequestUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RespondWalkRequestUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/ProfileView.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Interactor/RespondWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Presenter/RespondWalkPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Router/RespondWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/View/RespondWalkViewController.swift
Labels: feature

#111 [ui] 프로필 교환 에니메이션 적용
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Home/Main/Router/HomeRouter.swift
  SniffMeet/SniffMeet/Source/Home/Main/Router/PresentAnimator.swift
  SniffMeet/SniffMeet/Source/Home/Main/View/HomeViewController.swift
Labels: design

#110 [feat] SupabaseDatabase에 업데이트 로직 추가
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseManager.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseRequest.swift
Labels: feature

#116 [feat] 서버에서 사용자 정보 가져오는 유즈케이스 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseManager.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseRequest.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUserInfoRemoteUseCase.swift
Labels: feature

#118 [fix] 유저 정보 저장 및 로드 에러 수정
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Interactor/ProfileCreateInteractor.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Presenter/ProfileCreatePresenter.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Router/ProfileCreateRouter.swift
  SniffMeet/SniffMeet/Source/Common/Constant/Environment.swift
  SniffMeet/SniffMeet/Source/DTO/MateList.swift
  SniffMeet/SniffMeet/Source/Entity/UserInfo.swift
  SniffMeet/SniffMeet/Source/Home/Main/HomeModuleBuilder.swift
  SniffMeet/SniffMeet/Source/Persistence/SNMFileManager.swift
  SniffMeet/SniffMeet/Source/Repository/Auth/DataManager.swift
  SniffMeet/SniffMeet/Source/Supabase/Auth/SupabaseAuthManager.swift
  SniffMeet/SniffMeet/Source/UseCase/LoadUserInfoUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RespondMateRequestUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUserInfoRemoteUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUserInfoUseCase.swift
Labels: bug

#119 [feat] 메이트 리스트 뷰와 산책 신청 뷰 연결 작업
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/Design System/KeywordView.swift
  SniffMeet/SniffMeet/Source/Entity/Mate.swift
  SniffMeet/SniffMeet/Source/Entity/WalkRequest.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Presenter/MateListPresenter.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Router/MateListRouter.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/View/MateListViewController.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseManager.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseRequest.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestMateInfoUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestMateListUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Interactor/RequestWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Presenter/RequestWalkPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Router/RequestWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/CardPresentationController.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/ProfileView.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/RequestWalkViewController.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Presenter/RespondWalkPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/View/RespondWalkViewController.swift
Labels: feature, fix

#125 [fix] 키워드 뷰 잘림 문제 해결
  SniffMeet/SniffMeet/Source/Common/Design System/KeywordView.swift
Labels: bug

#122 [feat] 메이트 관계인 리스트 insert, update, fetch 구현
  SniffMeet/SniffMeet/Source/DTO/MateList.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Router/MateListRouter.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseManager.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseRequest.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestMateListUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RespondMateRequestUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUserInfoRemoteUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUserInfoUseCase.swift
Labels: feature

#127 [fix] 메이트 리스트 프로필 이미지가 캡슐로 보이는 현상 해결
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/Helper/Extension + UIImage.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/View/MateListViewController.swift
Labels: bug

#129 [chore, feat] Usecase 정리 및 폴더링, 연결 작업
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Interactor/ProfileCreateInteractor.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Router/ProfileCreateRouter.swift
  SniffMeet/SniffMeet/Source/DTO/UserInfoDTO.swift
  SniffMeet/SniffMeet/Source/UseCase/ComputeUseCase/CalculateTimeLimitUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/ComputeUseCase/ConvertLocationToTextUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/ComputeUseCase/ConvertToRequestAPSUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/ComputeUseCase/ConvertToRespondAPSUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/LoadUserInfoUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestLocationAuthUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestMateInfoUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestMateListUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestNotificationAuthUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestProfileImageUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestUserInfoRemoteUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestUserLocationUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestWalkUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUserInfoUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RespondUseCase/RespondMateRequestUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RespondUseCase/RespondWalkRequestUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/CreateAccountUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/RegisterDeviceTokenUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/RemoteSaveDeviceTokenUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/SaveProfileImageUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/SaveUserInfoUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Interactor/RespondWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Presenter/RespondWalkPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Router/RespondWalkRouter.swift
Labels: feature

#132 [fix] 메이트 리스트 목록 갱신 문제 해결
  SniffMeet/SniffMeet/Source/Mate/MateList/Presenter/MateListPresenter.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/View/MateListViewController.swift
Labels: fix

#135 [feat] 서버에 저장되는 이미지를 jpg로 압축하기
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Interactor/ProfileCreateInteractor.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/Presenter/ProfileCreatePresenter.swift
Labels: feature

#130 [feat] 서버에서 프로필 이미지 가져와 표시하기
  SniffMeet/SniffMeet/Source/DTO/MateList.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Interactor/MateListInteractor.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Presenter/MateListPresenter.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Router/MateListRouter.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/View/MateListViewController.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseManager.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseRequest.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestMateInfoUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestProfileImageUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestUserInfoRemoteUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Interactor/RequestWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Router/RequestWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Interactor/RespondWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Router/RespondWalkRouter.swift
Labels: feature

#138 [fix] 산책 신청 뷰에서 장소 선택 뷰로 전환이 안되는 문제 해결
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Presenter/SelectLocationPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Router/RequestWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Router/SelectLocationRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/LocationSelectionView.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/RequestWalkViewController.swift
Labels: fix
