Repository boostcampwm-2024/iOS03-SniffMeet, pull requests merged in 2024-12, with the labels that each got.

#139 [feat] 알림리스트 가져오는 UseCase 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/Constant/Environment.swift
  SniffMeet/SniffMeet/Source/DTO/NotiListDTO.swift
  SniffMeet/SniffMeet/Source/DTO/WalkNotiDTO.swift
  SniffMeet/SniffMeet/Source/Entity/WalkRequest.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseManager.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseRequest.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestMateListUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestNotiListUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/CreateAccountUseCase.swift
Labels: feature

#142 [feat] 산책 요청 수락 페이지에 이미지 Fetch하는 usecase 적용
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Interactor/RespondWalkInteractor.swift
Labels: feature

#146 [refactor] Push notification 데이터 구조 변경
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/App/AppDelegate.swift
  SniffMeet/SniffMeet/Source/App/AppRouter.swift
  SniffMeet/SniffMeet/Source/App/SceneDelegate.swift
  SniffMeet/SniffMeet/Source/DTO/WalkNotiDTO.swift
  SniffMeet/SniffMeet/Source/Entity/WalkAPS.swift
  SniffMeet/SniffMeet/Source/UseCase/ComputeUseCase/ConvertToRequestAPSUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/ComputeUseCase/ConvertToRespondAPSUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/ComputeUseCase/ConvertToWalkAPSUseCase.swift
Labels: refactor

#147 [feat] 정보 수정 뷰 ui 및 VIPER 모듈 초기 세팅
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/EditProfile/Interactor/ProfileEditInteractor.swift
  SniffMeet/SniffMeet/Source/EditProfile/Presenter/ProfileEditPresenter.swift
  SniffMeet/SniffMeet/Source/EditProfile/Router/ProfileEditRoutable.swift
  SniffMeet/SniffMeet/Source/EditProfile/View/ProfileEditViewController.swift
Labels: feature

#149 [feat] push notification 데이터 구조 수정
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/App/AppDelegate.swift
  SniffMeet/SniffMeet/Source/App/AppRouter.swift
  SniffMeet/SniffMeet/Source/App/SceneDelegate.swift
  SniffMeet/SniffMeet/Source/DTO/WalkNotiDTO.swift
  SniffMeet/SniffMeet/Source/Entity/WalkAPS.swift
  SniffMeet/SniffMeet/Source/UseCase/ComputeUseCase/ConvertToRequestAPSUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/ComputeUseCase/ConvertToRespondAPSUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/ComputeUseCase/ConvertToWalkAPSUseCase.swift
Labels: feature

#143 [feat] 산책 요청 뷰에서 선택한 장소 뷰 이동 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Supabase/SupabaseError.swift
  SniffMeet/SniffMeet/Source/UseCase/ComputeUseCase/ConvertLocationToTextUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestMateInfoUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Interactor/SelectLocationInteractor.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Presenter/SelectLocationPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/SelectLocationModuleBuildable.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Interactor/RespondWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Presenter/RespondMapPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Presenter/RespondWalkPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Router/RespondMapRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Router/RespondWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/View/RespondMapViewController.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/View/RespondWalkViewController.swift
Labels: feature, design

#154 [feat] device token 서버 등록 로직 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/App/AppDelegate.swift
  SniffMeet/SniffMeet/Source/Common/Constant/Environment.swift
  SniffMeet/SniffMeet/Source/DTO/SaveDeviceTokenDTO.swift
  SniffMeet/SniffMeet/Source/Home/Main/HomeModuleBuilder.swift
  SniffMeet/SniffMeet/Source/Home/Main/Interactor/HomeInteractor.swift
  SniffMeet/SniffMeet/Source/Home/Main/Presenter/HomePresenter.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/CheckFirstLaunchUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/RegisterDeviceTokenUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/RemoteSaveDeviceTokenUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/SaveFirstLaunchUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Interactor/RespondWalkInteractor.swift
Labels: feature

#157 [bug] 앱 진입 시점에서 검은 화면이 1초 보이는 문제 해결
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Resource/Base.lproj/LaunchScreen.storyboard
  SniffMeet/SniffMeet/Source/App/SceneDelegate.swift
  SniffMeet/SniffMeet/Source/App/SessionViewController.swift
  SniffMeet/SniffMeet/Source/Common/Design System/SNMFont.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Interactor/RespondWalkInteractor.swift
Labels: bug

#160 [bug] 단시간에 버튼의 연속적인 터치 이벤트 처리 관리
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileCreateViewController.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileInputViewController.swift
  SniffMeet/SniffMeet/Source/Common/Design System/EventConstant.swift
  SniffMeet/SniffMeet/Source/Home/Main/View/HomeViewController.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/View/MateListViewController.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/RequestWalkViewController.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/SelectLocationViewController.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/View/RespondWalkViewController.swift
Labels: bug

#159 [feat] notification cell 탭 시 화면 전환 로직 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/Helper/Extension + Date.swift
  SniffMeet/SniffMeet/Source/DTO/WalkAPSDTO.swift
  SniffMeet/SniffMeet/Source/DTO/WalkNotiDTO.swift
  SniffMeet/SniffMeet/Source/Entity/PushNotification.swift
  SniffMeet/SniffMeet/Source/Entity/WalkNoti.swift
  SniffMeet/SniffMeet/Source/Home/Alarm/Interactor/NotificationListInteractor.swift
  SniffMeet/SniffMeet/Source/Home/Alarm/Presenter/NotificationListPresenter.swift
  SniffMeet/SniffMeet/Source/Home/Alarm/Router/NotificationListRouter.swift
  SniffMeet/SniffMeet/Source/Home/Alarm/View/NotificationCell.swift
  SniffMeet/SniffMeet/Source/Home/Alarm/View/NotificationListViewController.swift
  SniffMeet/SniffMeet/Source/Home/Main/Router/HomeRouter.swift
Labels: feature

#163 [fix] 홈 뷰 키워드 정렬 문제 해결
  SniffMeet/SniffMeet/Source/Home/Main/View/ProfileCardView.swift
Labels: fix

#171 [feat] RequestWalkUseCase 적용
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Interactor/RequestWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Presenter/RequestWalkPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Router/RequestWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/LocationSelectionView.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/RequestWalkViewController.swift
Labels: feature

#172 [design] 라이트모드만 지원
  SniffMeet/SniffMeet/Resource/Info.plist
Labels: design

#168 [feat] 메이트 요청 거절 / 수락 기능 구현
  SniffMeet/SniffMeet/Source/DTO/DogProfileDTO.swift
  SniffMeet/SniffMeet/Source/Home/Main/Router/HomeRouter.swift
  SniffMeet/SniffMeet/Source/LocalNetwork/MPC/MPCManager.swift
  SniffMeet/SniffMeet/Source/Mate/RequestMate/Interactor/RequestMateInteractor.swift
  SniffMeet/SniffMeet/Source/Mate/RequestMate/Presenter/RequestMatePresenter.swift
  SniffMeet/SniffMeet/Source/Mate/RequestMate/Router/RequestMateRouter.swift
  SniffMeet/SniffMeet/Source/Mate/RequestMate/View/RequestMateViewController.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/SaveUserInfoUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/WalkLog/WalkLogList/View/WalkLogListViewController.swift
Labels: feature

#173 [feat] 산책 요청 응답 usecase 적용
  SniffMeet/SniffMeet/Source/UseCase/RespondUseCase/RespondWalkRequestUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Interactor/RespondWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Presenter/RespondWalkPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Router/RespondWalkRouter.swift
Labels: feature

#180 [fix] 산책 요청 & 응답 뷰에서 제출 버튼 지연 문제 해결
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Interactor/RequestWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/RequestWalkViewController.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Interactor/RespondWalkInteractor.swift
Labels: bug, fix

#181 [feat] 산책 요청 및 응답 Usecase에 walk_request 테이블을 조작하는 로직 추가
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/Constant/Environment.swift
  SniffMeet/SniffMeet/Source/DTO/WalkRequestDTO.swift
  SniffMeet/SniffMeet/Source/Entity/WalkNoti.swift
  SniffMeet/SniffMeet/Source/Supabase/Database/SupabaseDatabaseManager.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestWalkUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RespondUseCase/RespondWalkRequestUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Router/RequestWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Presenter/RespondWalkPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Router/RespondWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/View/RespondWalkViewController.swift
Labels: feature

#189 [fix] 산책 요청 뷰에서 키보드를 편집할 때 키보드가 올라감에 따라 뷰를 가리는 현상 해결
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Common/Helper/Extension + UIApplication.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/View/RequestWalkViewController.swift
Labels: bug, fix

#182 [fix] push notification 오류 해결
  SniffMeet/SniffMeet/Source/Entity/WalkNoti.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/LoadUserInfoUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Interactor/RespondWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Presenter/RespondWalkPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Router/RespondWalkRouter.swift
Labels: bug, fix

#187 [feat] TextField 조건 지정
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileCreateViewController.swift
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileInputViewController.swift
  SniffMeet/SniffMeet/Source/Home/EditProfile/View/ProfileEditViewController.swift
Labels: feature

#193 [fix] merge conflicts 해결 과정에서 누락된 내용 수정
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileInputViewController.swift
Labels: fix

#192 [feat] 프로필 드랍 에니메이션 적용
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Resource/Assets.xcassets/BrownPaw.imageset/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/BrownPaw.imageset/Pet Paw(2).png
  SniffMeet/SniffMeet/Resource/Assets.xcassets/BrownPaw.imageset/Pet Paw(3).png
  SniffMeet/SniffMeet/Resource/Assets.xcassets/NavyPaw.imageset/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/NavyPaw.imageset/Pet Paw(4).png
  SniffMeet/SniffMeet/Resource/Assets.xcassets/NavyPaw.imageset/Pet Paw(5).png
  SniffMeet/SniffMeet/Source/Common/Design System/ProfileDropAnimation.swift
  SniffMeet/SniffMeet/Source/Home/Main/Router/HomeRouter.swift
  SniffMeet/SniffMeet/Source/Mate/RequestMate/View/RequestMateViewController.swift
Labels: feature

#194 [design] 온보딩 화면 뷰 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Entity/OnBoardingPage.swift
  SniffMeet/SniffMeet/Source/OnBoarding/MainBoarding/View/OnBoardingPageViewController.swift
  SniffMeet/SniffMeet/Source/OnBoarding/MainBoarding/View/OnBoardingViewController.swift
Labels: feature, design

#199 [fix] 화면 전환 관련 오류 해결
  SniffMeet/SniffMeet/Source/App/AppDelegate.swift
  SniffMeet/SniffMeet/Source/App/AppRouter.swift
  SniffMeet/SniffMeet/Source/App/SceneDelegate.swift
  SniffMeet/SniffMeet/Source/App/SessionViewController.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Router/RespondWalkRouter.swift
Labels: bug, fix

#197 [fix] 변경된 디자인에 맞게 뷰 기능 변경
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/App/AppRouter.swift
  SniffMeet/SniffMeet/Source/Home/Main/Presenter/HomePresenter.swift
  SniffMeet/SniffMeet/Source/Home/Main/Router/HomeRouter.swift
  SniffMeet/SniffMeet/Source/Home/Main/View/HomeViewController.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Presenter/MateListPresenter.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Router/MateListRouter.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/View/AddMateButton.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/View/MateListViewController.swift
  SniffMeet/SniffMeet/Source/Tab/TabBarModuleBuilder.swift
  SniffMeet/SniffMeet/Source/Tab/View/TabBarController.swift
Labels: feature, fix

#200 [docs] README 수정
  README.md
Labels: documentation

#201 [feat] 온보딩 화면 동작 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Resource/Assets.xcassets/WalkingDog.imageset/Contents.json
  SniffMeet/SniffMeet/Resource/Assets.xcassets/WalkingDog.imageset/WalkingDog 1.png
  SniffMeet/SniffMeet/Resource/Assets.xcassets/WalkingDog.imageset/WalkingDog 2.png
  SniffMeet/SniffMeet/Resource/Assets.xcassets/WalkingDog.imageset/WalkingDog.png
  SniffMeet/SniffMeet/Resource/ProfileDrop.gif
  SniffMeet/SniffMeet/Source/App/AppRouter.swift
  SniffMeet/SniffMeet/Source/Entity/OnBoardingPage.swift
  SniffMeet/SniffMeet/Source/OnBoarding/MainBoarding/Interactor/OnBoardingInteractor.swift
  SniffMeet/SniffMeet/Source/OnBoarding/MainBoarding/Presenter/OnBoardingPresenter.swift
  SniffMeet/SniffMeet/Source/OnBoarding/MainBoarding/Router/OnBoardingRouter.swift
  SniffMeet/SniffMeet/Source/OnBoarding/MainBoarding/View/OnBoardingPageViewController.swift
  SniffMeet/SniffMeet/Source/OnBoarding/MainBoarding/View/OnBoardingViewController.swift
Labels: feature

#204 [fix] 온보딩 뷰 레이아웃 수정
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/OnBoarding/MainBoarding/View/OnBoardingPageViewController.swift
  SniffMeet/SniffMeet/Source/OnBoarding/MainBoarding/View/OnBoardingViewController.swift
Labels: fix

#209 [fix] profiledrop 연결 상태에 따른 button / alert 상태 변경
  SniffMeet/SniffMeet/Source/LocalNetwork/MPC/MPCManager.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Presenter/MateListPresenter.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Router/MateListRouter.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/View/AddMateButton.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/View/MateListViewController.swift
Labels: fix

#203 [feat] 이미지 캐싱 적용
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Mate/MateList/Router/MateListRouter.swift
  SniffMeet/SniffMeet/Source/Persistence/CacheManager.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Core/HTTPStatusCode.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Core/NetworkProvider.swift
  SniffMeet/SniffMeet/Source/SNMNetwork/Core/SNMNetworkResponse.swift
  SniffMeet/SniffMeet/Source/Supabase/Storage/SupabaseStorageManager.swift
  SniffMeet/SniffMeet/Source/Supabase/Storage/SupabaseStorageRequest.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestProfileImageUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Router/RequestWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Router/RespondWalkRouter.swift
Labels: feature

#206 [fix] 메이트 목록 테이블 뷰 셀 프로필 이미지 미스매칭 수정
  SniffMeet/SniffMeet/Source/Mate/MateList/Interactor/MateListInteractor.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/Presenter/MateListPresenter.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/View/MateListViewController.swift
Labels: fix

#208 [feat] 산책 수락, 거절 화면 구현
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/App/AppDelegate.swift
  SniffMeet/SniffMeet/Source/App/AppRouter.swift
  SniffMeet/SniffMeet/Source/App/SessionViewController.swift
  SniffMeet/SniffMeet/Source/Home/Alarm/Router/NotificationListRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Interactor/ProcessedWalkInteractor.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Presenter/ProcessedWalkPresenter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Router/ProcessedWalkRouter.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/View/ProcessedWalkViewController.swift
Labels: feature, design

#212 [fix] 알림에 닉네임이 기재되는 현상 해결
  SniffMeet/SniffMeet/Source/UseCase/RespondUseCase/RespondWalkRequestUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RespondWalk/Interactor/RespondWalkInteractor.swift
Labels: bug, fix

#214 [fix] 앱이 Non-running(Terminated) 상태일 때 Push Noti를 누르면 카드 뷰가 2번 present되는 현상 해결
  SniffMeet/SniffMeet/Source/App/AppDelegate.swift
  SniffMeet/SniffMeet/Source/App/SessionViewController.swift
Labels: bug, fix

#216 [feat] Disk Cache 적용
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Entity/ImageCacheable.swift
  SniffMeet/SniffMeet/Source/Persistence/CacheManager.swift
  SniffMeet/SniffMeet/Source/Persistence/SNMFileManager.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/LoadUserInfoUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/RequestUseCase/RequestProfileImageUseCase.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/SaveUserInfoUseCase.swift
Labels: feature

#218 [fix] SNM Toast 적용 범위 추가
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/Auth/CreateProfile/View/ProfileCreateViewController.swift
  SniffMeet/SniffMeet/Source/Common/Design System/SNMToast.swift
  SniffMeet/SniffMeet/Source/DTO/MateList.swift
  SniffMeet/SniffMeet/Source/Home/EditProfile/View/ProfileEditViewController.swift
  SniffMeet/SniffMeet/Source/Mate/MateList/View/MateListViewController.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/SaveUserInfoUseCase.swift
  SniffMeet/SniffMeet/Source/Walk/RequestWalk/Presenter/RequestWalkPresenter.swift
Labels: fix, UI

#219 [docs] 리드미 파일 업데이트
  README.md
Labels: documentation

#220 [feat] 최종 배포 전 더미 데이터 추가
  SniffMeet/SniffMeet.xcodeproj/project.pbxproj
  SniffMeet/SniffMeet/Source/DTO/MateListDTO.swift
  SniffMeet/SniffMeet/Source/Persistence/CacheManager.swift
  SniffMeet/SniffMeet/Source/UseCase/SaveUseCase/SaveUserInfoUseCase.swift
Labels: feature
